---
- name: Load variables specific to this OS
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags:
    - codedeploy

- include: "{{ ansible_os_family | lower }}.yml"
  tags:
    - codedeploy

- name: Get Instance Metadata | ec2
  action: ec2_metadata_facts
  tags:
    - codedeploy

- name: Get CodeDeploy | s3
  get_url:
    url: "https://aws-codedeploy-{{ ansible_ec2_placement_region }}.s3.amazonaws.com/latest/install"
    dest: /usr/local/sbin/codedeploy-install
  when: is_codedeploy_installed is failed
  tags:
    - codedeploy

- name: Codedeploy Install Binary | Permission Executable
  file:
    state: file
    path: /usr/local/sbin/codedeploy-install
    group: root
    owner: root
    mode: 0755
  when: is_codedeploy_installed is failed
  tags:
    - codedeploy

- name: Codedeploy Install
  become: true
  command: /usr/local/sbin/codedeploy-install auto
  when: is_codedeploy_installed is failed
  tags:
    - codedeploy
